name: cxt-skunkworks-server
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pandas=2.2.3
  - requests=2.32.3
  - python-dotenv=1.0.1
  - fastapi=0.115.6
  - uvicorn=0.34.0
  - pydantic=2.8.2
  - sqlalchemy=2.0.34
  - psycopg2=2.9.9
  - redis=5.0.8
  - numpy=1.26.4
  - pip
  - pip:
      - kafka-python==2.0.2
      - aiokafka==0.11.0
      - asyncpg==0.29.0
      - neo4j==5.24.0
      - timescaledb==0.1.1
      - openai==1.57.0
      - langchain==0.3.9
      - langchain-community==0.3.8
      - langchain-openai==0.2.9
      - geopy==2.4.1
      - shapely==2.0.6
      - geoalchemy2==0.15.2
      - celery==5.4.0
      - pytest==8.3.3
      - pytest-asyncio==0.24.0
      - httpx==0.28.1
